server:
  port: 8084

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: meme
          uri: lb://meme
          predicates:
            - Path=/memes/**
        - id: categoria-meme
          uri: lb://categoria-meme
          predicates:
            - Path=/categoria-meme/**
        - id: usuario
          uri: lb://usuario
          predicates:
            - Path=/usuarios/**
    discovery:
      locator:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true